name: Build APK
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fix gradlew from official
        run: |
          rm -f gradlew
          curl -Ls https://raw.githubusercontent.com/gradle/gradle/v8.7.0/gradlew -o gradlew
          chmod +x gradlew
          rm -f gradle/wrapper/gradle-wrapper.jar
          mkdir -p gradle/wrapper
          curl -Ls https://github.com/gradle/gradle/raw/v8.7.0/gradle/wrapper/gradle-wrapper.jar -o gradle/wrapper/gradle-wrapper.jar
          ls -lh gradlew gradle/wrapper/gradle-wrapper.jar
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
      - uses: android-actions/setup-android@v3
      - name: Build APK
        run: ./gradlew app:assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PijatIN-APK-111
          path: app/build/outputs/apk/debug/*.apk
